[package]
authors = ["jD91mZM2 <me@krake.one>"]
edition = "2018"
name = "generic-turing-machine"
version = "0.1.0"
[dependencies]
clap = "2.32.0"
failure = "0.1.3"
rowan = "0.1.1"
rustyline = "2.1.0"
